import test from "node:test";
import assert from "node:assert/strict";
import { buildAgentFrame, buildConnectFrame, createDeviceIdentity, exerciseGatewayContract, resolveGatewaySessionKey, validateGatewayConfig } from "../lib/integrations/openclaw-gateway-contract.mjs";
const config = { url: 'ws://127.0.0.1:18789', token: 'synthetic-token-12345', agentId: 'main', sessionKeyStrategy: 'issue' };
test('validates private transport and rejects weak or exposed configuration', () => { assert.equal(validateGatewayConfig(config).agentId, 'main'); assert.throws(() => validateGatewayConfig({ ...config, url: 'ws://public.example' }), /wss/); assert.throws(() => validateGatewayConfig({ ...config, token: 'x' }), /16/); });
test('signs the challenge and maps issue/run/fixed sessions', () => { const frame = buildConnectFrame({ challenge: 'challenge', token: config.token, device: createDeviceIdentity() }); assert.equal(frame.method, 'connect'); assert.ok(frame.params.device.signature.length > 40); assert.equal(resolveGatewaySessionKey({ strategy: 'issue', agentId: 'main', runId: 'r', issueId: 'i' }), 'agent:main:hq:issue:i'); assert.equal(buildAgentFrame({ agentId: 'main', runId: 'r', issueId: null, message: 'x', sessionKeyStrategy: 'run' }).params.idempotencyKey, 'r'); });
test('synthetic smoke covers task result, comment, notification and structured events', async () => { const calls = []; const transport = { request: async (frame, onEvent) => { calls.push(frame); if (frame.method === 'agent') { onEvent?.({ type: 'event', event: 'agent', seq: 1, payload: { runId: 'gateway-run', stream: 'assistant', text: 'COMMENT_OK NOTIFY_OK TASK_DONE' } }); return { runId: 'gateway-run' }; } return { ok: true }; } }; const result = await exerciseGatewayContract({ config, transport, run: { runId: 'run-1', issueId: 'issue-1', message: 'work' } }); assert.deepEqual(calls.map((x) => x.method), ['connect', 'agent', 'agent.wait']); assert.match(result.events[0].text, /COMMENT_OK.*NOTIFY_OK.*TASK_DONE/); assert.equal(result.factoryEntrypoint, 'scripts/openclaw-factory.mjs'); assert.equal(result.workerEntrypoint, './run.sh'); });
test('pairing is approved once then retried with the same idempotency key', async () => { let attempts = 0; const keys = []; const transport = { request: async (frame) => { if (frame.method === 'agent') { keys.push(frame.params.idempotencyKey); if (attempts++ === 0) { const error = new Error('pairing required'); error.code = 'PAIRING_REQUIRED'; error.requestId = 'pair-1'; throw error; } return { runId: 'gateway-run' }; } return { ok: true }; } }; await exerciseGatewayContract({ config, transport, run: { runId: 'run-2', issueId: 'issue-2', message: 'work' } }); assert.deepEqual(keys, ['run-2', 'run-2']); });
test('new session, timeout, duplicate run, and revoked credential cases are observable', async () => { assert.notEqual(resolveGatewaySessionKey({ strategy: 'run', agentId: 'main', runId: 'new-run', issueId: 'i' }), resolveGatewaySessionKey({ strategy: 'run', agentId: 'main', runId: 'old-run', issueId: 'i' })); const timeout = { request: () => new Promise(() => {}) }; await assert.rejects(exerciseGatewayContract({ config, transport: timeout, timeoutMs: 5, run: { runId: 'timeout', issueId: 'i', message: 'x' } }), (e) => e.code === 'GATEWAY_TIMEOUT'); const revoked = { request: async () => { const e = new Error('revoked'); e.code = 'AUTH_REVOKED'; throw e; } }; await assert.rejects(exerciseGatewayContract({ config, transport: revoked, run: { runId: 'revoked', issueId: 'i', message: 'x' } }), (e) => e.code === 'AUTH_REVOKED'); const frame = buildAgentFrame({ agentId: 'main', runId: 'duplicate', issueId: 'i', message: 'x' }); assert.equal(frame.params.idempotencyKey, 'duplicate'); });
